services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    networks:
      - backend
    restart: unless-stopped
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - backend
    restart: unless-stopped
  keycloak:
    image: quay.io/keycloak/keycloak:nightly
    container_name: keycloak
    command: start-dev # --auto-build --import-realm
    volumes:
      - ./import:/opt/keycloak/data/import
      - ./themes:/opt/keycloak/themes
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_PROXY: edge

      KC_HTTP_ENABLED: true

      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/dev
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: postgres
    ports:
      - "7070:8080"
      - "7071:8443"
    networks:
      - backend
  tomcat:
    image: tomcat:9-alpine
    ports:
      - "8081:8080"
    networks:
      - backend
networks:
  backend:
    driver: bridge
    name: backend
    external: true
